# Generate one add_test() per case reported by a test runner's --list.
#
# Run as a script at build time (see tests/CMakeLists.txt): only the linked
# binary knows which cases are actually compiled in, since some are guarded by
# preprocessor conditionals.
#
# SPDX-License-Identifier: Apache-2.0

execute_process(
    COMMAND ${RUNNER} --list
    OUTPUT_VARIABLE _out
    RESULT_VARIABLE _rc
    OUTPUT_STRIP_TRAILING_WHITESPACE)

if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "test discovery failed: ${RUNNER} --list returned ${_rc}")
endif()

string(REPLACE "\n" ";" _names "${_out}")

set(_content "# generated by DiscoverTests.cmake -- do not edit\n")
set(_count 0)
foreach(_n ${_names})
    string(STRIP "${_n}" _n)
    if(_n STREQUAL "")
        continue()
    endif()
    # The legacy add_test(<name> <cmd> <args>) form is required here: this file
    # is read by CTest at test time, where add_test is CTest's own scripting
    # command and the NAME/COMMAND keyword form is not understood.
    string(APPEND _content
        "add_test(timui.core.${_n} \"${RUNNER}\" ${_n})\n"
        "set_tests_properties(timui.core.${_n} PROPERTIES WORKING_DIRECTORY \"${WORKDIR}\")\n")
    math(EXPR _count "${_count} + 1")
endforeach()

if(_count EQUAL 0)
    message(FATAL_ERROR "test discovery found no cases in ${RUNNER}")
endif()

file(WRITE ${OUTFILE} "${_content}")
message(STATUS "discovered ${_count} tests from ${RUNNER}")
