/*
 * test_main.c — registers and runs all timui.h unit tests.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#include <stdio.h>
#include <string.h>

#include "test.h"

int timui_test_failures = 0;

int main(int argc, char **argv){
    typedef struct { const char *name; void (*fn)(void); } test_case;
    test_case tests[] = {
        { "test_rect_cuts", test_rect_cuts },
        { "test_rect_cut_null_safe", test_rect_cut_null_safe },
        { "test_rect_cut_extreme_origin_safe", test_rect_cut_extreme_origin_safe },
        { "test_rect_cut_mutated_origin_safe", test_rect_cut_mutated_origin_safe },
        { "test_rect_split", test_rect_split },
        { "test_rect_split_extreme_origin_safe", test_rect_split_extreme_origin_safe },
        { "test_rect_inset_clamp", test_rect_inset_clamp },
        { "test_rect_inset_pad_extreme_safe", test_rect_inset_pad_extreme_safe },
        { "test_ids_stable", test_ids_stable },
        { "test_error_string", test_error_string },
        { "test_version", test_version },
        { "test_config_init_defaults", test_config_init_defaults },
        { "test_open_rejects_config_version_mismatch", test_open_rejects_config_version_mismatch },
        { "test_default_allocator", test_default_allocator },
        { "test_arena_alloc_reset", test_arena_alloc_reset },
        { "test_arena_oom", test_arena_oom },
        { "test_arena_alignment", test_arena_alignment },
        { "test_arena_alignment_uses_base_address", test_arena_alignment_uses_base_address },
        { "test_arena_custom_allocator", test_arena_custom_allocator },
        { "test_partial_allocator_rejected", test_partial_allocator_rejected },
        { "test_arena_invalid_args", test_arena_invalid_args },
        { "test_arena_non_pow2_align", test_arena_non_pow2_align },
        { "test_str_from_cstr", test_str_from_cstr },
        { "test_str_copy_bounded", test_str_copy_bounded },
        { "test_str_slice", test_str_slice },
        { "test_str_eq_cstr", test_str_eq_cstr },
        { "test_str_invalid_utf8_passthrough", test_str_invalid_utf8_passthrough },
        { "test_id_stack_stable", test_id_stack_stable },
        { "test_id_stack_nesting_order", test_id_stack_nesting_order },
        { "test_id_stack_pop_restore", test_id_stack_pop_restore },
        { "test_id_stack_empty_and_grow", test_id_stack_empty_and_grow },
        { "test_id_stack_push_ok", test_id_stack_push_ok },
        { "test_id_stack_push_oom", test_id_stack_push_oom },
        { "test_id_stack_init_overflow_guard", test_id_stack_init_overflow_guard },
        { "test_msgq_order_and_copy", test_msgq_order_and_copy },
        { "test_msgq_full_predictable", test_msgq_full_predictable },
        { "test_msgq_variable_sizes", test_msgq_variable_sizes },
        { "test_msgq_null_data_rejected", test_msgq_null_data_rejected },
        { "test_mpsc_fifo_single", test_mpsc_fifo_single },
        { "test_mpsc_multi_producer", test_mpsc_multi_producer },
        { "test_mpsc_overflow_guard", test_mpsc_overflow_guard },
        { "test_mpsc_null_data_rejected", test_mpsc_null_data_rejected },
        { "test_mpsc_destroy_is_idempotent", test_mpsc_destroy_is_idempotent },
        { "test_mpsc_serializes_custom_allocator", test_mpsc_serializes_custom_allocator },
        { "test_fake_capture_output", test_fake_capture_output },
        { "test_fake_inject_input", test_fake_inject_input },
        { "test_fake_grows", test_fake_grows },
        { "test_transport_close_hook", test_transport_close_hook },
        { "test_default_mode_waits_for_input", test_default_mode_waits_for_input },
        { "test_external_poll_never_waits", test_external_poll_never_waits },
        { "test_external_poll_still_reads_ready_input", test_external_poll_still_reads_ready_input },
        { "test_external_poll_exposes_fd_and_timeout", test_external_poll_exposes_fd_and_timeout },
        { "test_open_failure_clears_output_handle", test_open_failure_clears_output_handle },
        { "test_open_for_test_failure_does_not_close_injected_transport", test_open_for_test_failure_does_not_close_injected_transport },
        { "test_write_all_under_backpressure", test_write_all_under_backpressure },
        { "test_screen_enter_emits_modes", test_screen_enter_emits_modes },
        { "test_screen_exit_reverses", test_screen_exit_reverses },
        { "test_kitty_keyboard_mode_enter_exit", test_kitty_keyboard_mode_enter_exit },
        { "test_title_rejects_controls", test_title_rejects_controls },
        { "test_input_arrows", test_input_arrows },
        { "test_input_function_keys", test_input_function_keys },
        { "test_input_tilde_edit_keys", test_input_tilde_edit_keys },
        { "test_input_control_chars", test_input_control_chars },
        { "test_input_text_and_alt", test_input_text_and_alt },
        { "test_input_partial_then_complete", test_input_partial_then_complete },
        { "test_input_timeout_before_new_bytes", test_input_timeout_before_new_bytes },
        { "test_input_utf8", test_input_utf8 },
        { "test_input_invalid_safe", test_input_invalid_safe },
        { "test_mouse_press_release", test_mouse_press_release },
        { "test_mouse_sgr_cb3_is_release", test_mouse_sgr_cb3_is_release },
        { "test_mouse_malformed_sgr_ignored", test_mouse_malformed_sgr_ignored },
        { "test_mouse_wheel_and_motion", test_mouse_wheel_and_motion },
        { "test_mouse_wheel_not_clicked", test_mouse_wheel_not_clicked },
        { "test_mouse_motion_not_clicked", test_mouse_motion_not_clicked },
        { "test_mouse_clicked_reports_press_cell", test_mouse_clicked_reports_press_cell },
        { "test_focus_events", test_focus_events },
        { "test_bracketed_paste", test_bracketed_paste },
        { "test_input_esc_resync_no_loss", test_input_esc_resync_no_loss },
        { "test_input_utf8_resync_no_loss", test_input_utf8_resync_no_loss },
        { "test_input_csi_ss3_non_ascii_resync_no_loss", test_input_csi_ss3_non_ascii_resync_no_loss },
        { "test_mouse_wheel_with_mods", test_mouse_wheel_with_mods },
        { "test_input_nul_ignored", test_input_nul_ignored },
        { "test_paste_cross_feed_three_fragments", test_paste_cross_feed_three_fragments },
        { "test_paste_empty_no_event", test_paste_empty_no_event },
        { "test_input_utf8_overlong_rejected", test_input_utf8_overlong_rejected },
        { "test_input_utf8_invalid_lead_immediate", test_input_utf8_invalid_lead_immediate },
        { "test_input_esc_mid_csi_restarts", test_input_esc_mid_csi_restarts },
        { "test_input_truncated_csi_ss3_timeout_resyncs", test_input_truncated_csi_ss3_timeout_resyncs },
        { "test_input_csi_subparam_ignored", test_input_csi_subparam_ignored },
        { "test_termios_raw_and_restore", test_termios_raw_and_restore },
        { "test_termios_setattr_failure", test_termios_setattr_failure },
        { "test_termios_enter_failure_clears_state", test_termios_enter_failure_clears_state },
        { "test_open_restores_input_fd_flags", test_open_restores_input_fd_flags },
        { "test_open_fails_when_nonblock_set_fails", test_open_fails_when_nonblock_set_fails },
        { "test_restore_terminal_restores_input_fd_flags", test_restore_terminal_restores_input_fd_flags },
        { "test_open_restores_previous_signal_handler", test_open_restores_previous_signal_handler },
        { "test_open_enters_screen_when_only_output_is_tty", test_open_enters_screen_when_only_output_is_tty },
        { "test_open_fails_when_raw_mode_fails", test_open_fails_when_raw_mode_fails },
        { "test_open_rejects_invalid_fds", test_open_rejects_invalid_fds },
        { "test_term_size_query", test_term_size_query },
        { "test_open_falls_back_from_zero_term_size", test_open_falls_back_from_zero_term_size },
        { "test_term_size_not_a_tty", test_term_size_not_a_tty },
        { "test_term_size_pixels_query", test_term_size_pixels_query },
        { "test_term_size_pixels_not_a_tty", test_term_size_pixels_not_a_tty },
        { "test_caps_modern_kitty_family", test_caps_modern_kitty_family },
        { "test_caps_multiplexer_reduces", test_caps_multiplexer_reduces },
        { "test_caps_multiplexer_kitty_passthrough", test_caps_multiplexer_kitty_passthrough },
        { "test_caps_unknown_fallback", test_caps_unknown_fallback },
        { "test_caps_force_masks", test_caps_force_masks },
        { "test_caps_image_protocol_selection", test_caps_image_protocol_selection },
        { "test_caps_iterm2_detects_image_protocol", test_caps_iterm2_detects_image_protocol },
        { "test_caps_report_explains_multiplexer_reductions", test_caps_report_explains_multiplexer_reductions },
        { "test_caps_report_notes_ssh_and_safe_fallback", test_caps_report_notes_ssh_and_safe_fallback },
        { "test_kitty_csi_u_plain", test_kitty_csi_u_plain },
        { "test_kitty_csi_u_with_mods", test_kitty_csi_u_with_mods },
        { "test_kitty_special_codes", test_kitty_special_codes },
        { "test_kitty_mods_on_arrows", test_kitty_mods_on_arrows },
        { "test_sync_begin_end_bytes", test_sync_begin_end_bytes },
        { "test_cursor_hide_show_bytes", test_cursor_hide_show_bytes },
        { "test_cells_init_clear", test_cells_init_clear },
        { "test_cells_put_get_roundtrip", test_cells_put_get_roundtrip },
        { "test_cells_resize", test_cells_resize },
        { "test_cells_init_overflow_guard", test_cells_init_overflow_guard },
        { "test_cells_resize_keeps_original_allocator", test_cells_resize_keeps_original_allocator },
        { "test_resize_oom_keeps_dims", test_resize_oom_keeps_dims },
        { "test_resize_oom_rollback_failure_keeps_dims", test_resize_oom_rollback_failure_keeps_dims },
        { "test_utf8_decode", test_utf8_decode },
        { "test_utf8_width", test_utf8_width },
        { "test_utf8_decode_above_max", test_utf8_decode_above_max },
        { "test_grapheme_next_prev", test_grapheme_next_prev },
        { "test_grapheme_width", test_grapheme_width },
        { "test_utf8_decode_impossible_leads", test_utf8_decode_impossible_leads },
        { "test_draw_text", test_draw_text },
        { "test_draw_text_truncated_utf8_replacement", test_draw_text_truncated_utf8_replacement },
        { "test_draw_fill", test_draw_fill },
        { "test_draw_fill_extreme_negative_rect_empty", test_draw_fill_extreme_negative_rect_empty },
        { "test_draw_box_single", test_draw_box_single },
        { "test_draw_box_ascii", test_draw_box_ascii },
        { "test_draw_hline_vline", test_draw_hline_vline },
        { "test_draw_box_clamps_oversized", test_draw_box_clamps_oversized },
        { "test_render_diff_exact", test_render_diff_exact },
        { "test_render_unchanged_emits_nothing", test_render_unchanged_emits_nothing },
        { "test_render_diff_narrow_to_wide", test_render_diff_narrow_to_wide },
        { "test_render_diff_wide_to_narrow", test_render_diff_wide_to_narrow },
        { "test_draw_overwrites_repair_wide_pairs", test_draw_overwrites_repair_wide_pairs },
        { "test_render_hyperlink_uri_change", test_render_hyperlink_uri_change },
        { "test_render_hyperlink_closes_at_frame_end", test_render_hyperlink_closes_at_frame_end },
        { "test_render_controls_are_not_emitted_as_glyphs", test_render_controls_are_not_emitted_as_glyphs },
        { "test_draw_wide_glyph_left_of_buffer_does_not_blank_edge", test_draw_wide_glyph_left_of_buffer_does_not_blank_edge },
        { "test_render_black_vs_default", test_render_black_vs_default },
        { "test_render_cursor_visible", test_render_cursor_visible },
        { "test_render_cursor_hidden", test_render_cursor_hidden },
        { "test_render_cursor_extreme_coords_safe", test_render_cursor_extreme_coords_safe },
        { "test_frame_lifecycle", test_frame_lifecycle },
        { "test_begin_result_statuses", test_begin_result_statuses },
        { "test_begin_result_transport_error", test_begin_result_transport_error },
        { "test_invalidate_resets_terminal_state_cache", test_invalidate_resets_terminal_state_cache },
        { "test_full_redraw_repaints_unchanged_frame", test_full_redraw_repaints_unchanged_frame },
        { "test_frame_quit_flag", test_frame_quit_flag },
        { "test_events_dropped", test_events_dropped },
        { "test_begin_preserves_focus_events", test_begin_preserves_focus_events },
        { "test_interact_click", test_interact_click },
        { "test_interact_hover_only", test_interact_hover_only },
        { "test_interact_release_outside_does_not_click", test_interact_release_outside_does_not_click },
        { "test_interact_extreme_rect_hit_test", test_interact_extreme_rect_hit_test },
        { "test_interact_tab_cycles", test_interact_tab_cycles },
        { "test_interact_keyboard_activate", test_interact_keyboard_activate },
        { "test_interact_tab_many_widgets", test_interact_tab_many_widgets },
        { "test_theme_dos_blue", test_theme_dos_blue },
        { "test_theme_mono_default", test_theme_mono_default },
        { "test_theme_style_lookup", test_theme_style_lookup },
        { "test_theme_slot_coverage", test_theme_slot_coverage },
        { "test_theme_slot_out_of_range", test_theme_slot_out_of_range },
        { "test_stylesheet_parse_specificity_states", test_stylesheet_parse_specificity_states },
        { "test_stylesheet_source_order_tiebreak", test_stylesheet_source_order_tiebreak },
        { "test_stylesheet_state_matching", test_stylesheet_state_matching },
        { "test_stylesheet_malformed_input", test_stylesheet_malformed_input },
        { "test_stylesheet_oom", test_stylesheet_oom },
        { "test_stylesheet_applies_button_states", test_stylesheet_applies_button_states },
        { "test_stylesheet_applies_list_selection", test_stylesheet_applies_list_selection },
        { "test_stylesheet_explicit_label_ignores_sheet", test_stylesheet_explicit_label_ignores_sheet },
        { "test_stylesheet_clear_and_explicit_input_style", test_stylesheet_clear_and_explicit_input_style },
        { "test_button_click", test_button_click },
        { "test_button_click_press_release_same_frame", test_button_click_press_release_same_frame },
        { "test_button_same_frame_release_outside_no_click", test_button_same_frame_release_outside_no_click },
        { "test_button_outside_no_click", test_button_outside_no_click },
        { "test_button_label_clipped", test_button_label_clipped },
        { "test_checkbox_toggles", test_checkbox_toggles },
        { "test_radio_selects", test_radio_selects },
        { "test_checkbox_label_clipped", test_checkbox_label_clipped },
        { "test_panel_body_rect", test_panel_body_rect },
        { "test_panel_title_clipped", test_panel_title_clipped },
        { "test_input_types_and_submits", test_input_types_and_submits },
        { "test_input_line_utf8_no_split", test_input_line_utf8_no_split },
        { "test_input_line_utf8_backspace", test_input_line_utf8_backspace },
        { "test_input_line_grapheme_backspace", test_input_line_grapheme_backspace },
        { "test_input_line_buf_clipped", test_input_line_buf_clipped },
        { "test_input_line_buf_clamps_unterminated", test_input_line_buf_clamps_unterminated },
        { "test_input_field_edit", test_input_field_edit },
        { "test_input_field_same_frame_edit_order", test_input_field_same_frame_edit_order },
        { "test_input_field_grapheme_edit", test_input_field_grapheme_edit },
        { "test_input_field_cursor_clamped_to_text", test_input_field_cursor_clamped_to_text },
        { "test_input_field_clamps_unterminated", test_input_field_clamps_unterminated },
        { "test_input_field_multi_submit", test_input_field_multi_submit },
        { "test_input_field_paste", test_input_field_paste },
        { "test_input_field_paste_split", test_input_field_paste_split },
        { "test_input_field_paste_split_utf8", test_input_field_paste_split_utf8 },
        { "test_input_field_paste_drops_controls", test_input_field_paste_drops_controls },
        { "test_input_field_paste_invalid_utf8_replaced", test_input_field_paste_invalid_utf8_replaced },
        { "test_paste_preserves_text_order", test_paste_preserves_text_order },
        { "test_input_field_paste_enter_order", test_input_field_paste_enter_order },
        { "test_input_field_text_burst", test_input_field_text_burst },
        { "test_input_field_kitty_csi_u_printable", test_input_field_kitty_csi_u_printable },
        { "test_input_field_kitty_csi_u_shifted_printable", test_input_field_kitty_csi_u_shifted_printable },
        { "test_input_field_emacs", test_input_field_emacs },
        { "test_input_field_styled", test_input_field_styled },
        { "test_mouse_click_hyperlink", test_mouse_click_hyperlink },
        { "test_input_field_scroll", test_input_field_scroll },
        { "test_input_field_guards", test_input_field_guards },
        { "test_focused_input_cursor", test_focused_input_cursor },
        { "test_set_focus_programmatic", test_set_focus_programmatic },
        { "test_text_input_accessor", test_text_input_accessor },
        { "test_cursor_no_diff_desync", test_cursor_no_diff_desync },
        { "test_listbox_down_key", test_listbox_down_key },
        { "test_listbox_click_selects", test_listbox_click_selects },
        { "test_listbox_selected_clamped", test_listbox_selected_clamped },
        { "test_listbox_label_clipped", test_listbox_label_clipped },
        { "test_message_box_miss", test_message_box_miss },
        { "test_message_box_button_clamped", test_message_box_button_clamped },
        { "test_fuzz_parser_random_stream", test_fuzz_parser_random_stream },
        { "test_fuzz_parser_adversarial", test_fuzz_parser_adversarial },
        { "test_clip_restricts_drawing", test_clip_restricts_drawing },
        { "test_clip_nested_intersect", test_clip_nested_intersect },
        { "test_clip_stack_overflow_preserves_pop_symmetry", test_clip_stack_overflow_preserves_pop_symmetry },
        { "test_clip_wide_glyph_requires_full_width", test_clip_wide_glyph_requires_full_width },
        { "test_clip_extreme_rect_does_not_overflow", test_clip_extreme_rect_does_not_overflow },
        { "test_clip_pop_underflow_safe", test_clip_pop_underflow_safe },
        { "test_menu_open_and_select", test_menu_open_and_select },
        { "test_menu_outside_click_closes", test_menu_outside_click_closes },
        { "test_modal_traps_background", test_modal_traps_background },
        { "test_hyperlink_renders_osc8", test_hyperlink_renders_osc8 },
        { "test_hyperlink_uri_controls_are_sanitized", test_hyperlink_uri_controls_are_sanitized },
        { "test_esc_timeout_flushes", test_esc_timeout_flushes },
        { "test_esc_arrow_not_delayed", test_esc_arrow_not_delayed },
        { "test_scroll_view_clips", test_scroll_view_clips },
        { "test_theme_modern_light", test_theme_modern_light },
        { "test_clipboard_osc52", test_clipboard_osc52 },
        { "test_clipboard_huge_len_safe", test_clipboard_huge_len_safe },
        { "test_keymap_bind", test_keymap_bind },
        { "test_keymap_bind_overflow", test_keymap_bind_overflow },
        { "test_keymap_hit_multi_binding", test_keymap_hit_multi_binding },
        { "test_table_renders", test_table_renders },
        { "test_table_draws_keyboard_selection_same_frame", test_table_draws_keyboard_selection_same_frame },
        { "test_tree_renders", test_tree_renders },
        { "test_tree_draws_keyboard_selection_same_frame", test_tree_draws_keyboard_selection_same_frame },
        { "test_tree_deep_safe", test_tree_deep_safe },
        { "test_tree_controlled_no_write_without_change", test_tree_controlled_no_write_without_change },
        { "test_table_ex_renders", test_table_ex_renders },
        { "test_table_ex_down_key", test_table_ex_down_key },
        { "test_table_ex_hscroll", test_table_ex_hscroll },
        { "test_table_ex_wheel_only_when_hovered", test_table_ex_wheel_only_when_hovered },
        { "test_tree_scroll_hides_collapsed", test_tree_scroll_hides_collapsed },
        { "test_tree_scroll_wheel_only_when_hovered", test_tree_scroll_wheel_only_when_hovered },
        { "test_tree_scroll_windows", test_tree_scroll_windows },
        { "test_cmd_palette_filter", test_cmd_palette_filter },
        { "test_cmd_palette_draws_keyboard_selection_same_frame", test_cmd_palette_draws_keyboard_selection_same_frame },
        { "test_combobox_filter_select_activate", test_combobox_filter_select_activate },
        { "test_combobox_no_match_and_clamp", test_combobox_no_match_and_clamp },
        { "test_combobox_mouse_accept_duplicate", test_combobox_mouse_accept_duplicate },
        { "test_combobox_query_cap_utf8_no_split", test_combobox_query_cap_utf8_no_split },
        { "test_combobox_escape_closes_without_clearing_query", test_combobox_escape_closes_without_clearing_query },
        { "test_combobox_cursor_movement_updates_state", test_combobox_cursor_movement_updates_state },
        { "test_combobox_clamps_cursor_to_query_len_before_edit", test_combobox_clamps_cursor_to_query_len_before_edit },
        { "test_combobox_guards_empty_options", test_combobox_guards_empty_options },
        { "test_combobox_accept_cap_limited", test_combobox_accept_cap_limited },
        { "test_toast_order_timeout_dismiss", test_toast_order_timeout_dismiss },
        { "test_toast_clips_stack", test_toast_clips_stack },
        { "test_toast_guards", test_toast_guards },
        { "test_split_pane_horizontal_drag_clamps_minmax", test_split_pane_horizontal_drag_clamps_minmax },
        { "test_split_pane_vertical_geometry_and_guards", test_split_pane_vertical_geometry_and_guards },
        { "test_split_pane_mut_writeback_only_on_drag", test_split_pane_mut_writeback_only_on_drag },
        { "test_split_pane_drag_requires_divider_press", test_split_pane_drag_requires_divider_press },
        { "test_split_pane_wheel_does_not_drag", test_split_pane_wheel_does_not_drag },
        { "test_snapshot_row_eq", test_snapshot_row_eq },
        { "test_snapshot_grid_full", test_snapshot_grid_full },
        { "test_snapshot_grid_eq_same", test_snapshot_grid_eq_same },
        { "test_snapshot_grid_eq_diff", test_snapshot_grid_eq_diff },
        { "test_snapshot_grid_eq_dim", test_snapshot_grid_eq_dim },
        { "test_snapshot_goldens", test_snapshot_goldens },
        { "test_snapshot_grid_returns_would_be_length", test_snapshot_grid_returns_would_be_length },
        { "test_snapshot_grid_size_query", test_snapshot_grid_size_query },
#ifdef TIMUI_WITH_VTERM_TESTS
        /* Tier A libvterm round-trip tests. Registration is explicit so an
         * ambient <vterm.h> cannot make non-vterm test binaries reference
         * symbols that are not linked. */
        { "test_vt_plain_text", test_vt_plain_text },
        { "test_vt_rainbow", test_vt_rainbow },
        { "test_vt_attrs", test_vt_attrs },
        { "test_vt_box_glyphs", test_vt_box_glyphs },
        { "test_vt_fill", test_vt_fill },
        { "test_vt_hyperlink", test_vt_hyperlink },
        { "test_vt_partial_update", test_vt_partial_update },
        { "test_vt_wide_glyph", test_vt_wide_glyph },
#endif
        { "test_text_area_renders", test_text_area_renders },
        { "test_text_area_wraps_at_viewport_edge",
          test_text_area_wraps_at_viewport_edge },
        { "test_text_area_utf8_no_split", test_text_area_utf8_no_split },
        { "test_text_area_utf8_backspace", test_text_area_utf8_backspace },
        { "test_text_area_paste_preserves_newline", test_text_area_paste_preserves_newline },
        { "test_text_area_zero_cap_safe", test_text_area_zero_cap_safe },
        { "test_text_area_cursor_overcap_safe", test_text_area_cursor_overcap_safe },
        { "test_text_area_cursor_clamped_to_text", test_text_area_cursor_clamped_to_text },
        { "test_text_area_clamps_unterminated", test_text_area_clamps_unterminated },
        { "test_text_area_cursor_edit", test_text_area_cursor_edit },
        { "test_text_area_same_frame_edit_order", test_text_area_same_frame_edit_order },
        { "test_text_area_scroll_applies_before_draw", test_text_area_scroll_applies_before_draw },
        { "test_text_area_cursor_utf8", test_text_area_cursor_utf8 },
        { "test_text_area_grapheme_edit", test_text_area_grapheme_edit },
        { "test_text_area_submit_plain_enter", test_text_area_submit_plain_enter },
        { "test_text_area_ex_returns_state", test_text_area_ex_returns_state },
        { "test_text_area_shift_enter_inserts_newline", test_text_area_shift_enter_inserts_newline },
        { "test_text_area_multi_enter_segments", test_text_area_multi_enter_segments },
        { "test_text_area_paste_preserves_newlines", test_text_area_paste_preserves_newlines },
        { "test_text_area_submit_unfocused_noop", test_text_area_submit_unfocused_noop },
        { "test_text_area_shift_enter_then_plain_enter", test_text_area_shift_enter_then_plain_enter },
        { "test_text_area_wrapper_enter_inserts_newline", test_text_area_wrapper_enter_inserts_newline },
        { "test_conpty_unsupported", test_conpty_unsupported },
        { "test_conpty_chunk_and_size_guards", test_conpty_chunk_and_size_guards },
        { "test_kitty_graphics_rejects_invalid_png", test_kitty_graphics_rejects_invalid_png },
        { "test_kitty_graphics_transmit", test_kitty_graphics_transmit },
        { "test_kitty_png_rgba_uses_png_payload", test_kitty_png_rgba_uses_png_payload },
        { "test_kitty_transmit_does_not_duplicate_payload", test_kitty_transmit_does_not_duplicate_payload },
        { "test_kitty_graphics_chunking", test_kitty_graphics_chunking },
        { "test_signal_restore", test_signal_restore },
        { "test_kitty_graphics_clip", test_kitty_graphics_clip },
        { "test_image_png_ihdr_over_int_ignored", test_image_png_ihdr_over_int_ignored },
        { "test_kitty_clipped_invalid_visible_no_image_escape", test_kitty_clipped_invalid_visible_no_image_escape },
        { "test_kitty_graphics_clip_horizontal_source_rect", test_kitty_graphics_clip_horizontal_source_rect },
        { "test_kitty_graphics_respects_active_clip", test_kitty_graphics_respects_active_clip },
        { "test_kitty_graphics_placeholder", test_kitty_graphics_placeholder },
        { "test_kitty_placement_overflow_placeholder", test_kitty_placement_overflow_placeholder },
        { "test_image_protocol_force_none_placeholder", test_image_protocol_force_none_placeholder },
        { "test_sixel_malformed_png_still_placeholder", test_sixel_malformed_png_still_placeholder },
        { "test_sixel_plain_png_decodes_to_dcs", test_sixel_plain_png_decodes_to_dcs },
        { "test_sixel_oversized_png_still_placeholder", test_sixel_oversized_png_still_placeholder },
        { "test_image_from_rgba_copies_rows_and_dimensions", test_image_from_rgba_copies_rows_and_dimensions },
        { "test_image_from_rgba_rejects_invalid_inputs", test_image_from_rgba_rejects_invalid_inputs },
        { "test_image_from_png_rgba_copies_png_and_pixels", test_image_from_png_rgba_copies_png_and_pixels },
        { "test_image_from_png_rgba_rejects_invalid_inputs", test_image_from_png_rgba_rejects_invalid_inputs },
        { "test_image_png_byte_limit_rejects_oversized_inputs", test_image_png_byte_limit_rejects_oversized_inputs },
        { "test_sixel_rgba_emits_dcs_single_band", test_sixel_rgba_emits_dcs_single_band },
        { "test_sixel_png_rgba_emits_dcs_from_pixels", test_sixel_png_rgba_emits_dcs_from_pixels },
        { "test_sixel_rejects_short_strided_sidecar", test_sixel_rejects_short_strided_sidecar },
        { "test_sixel_rgba_alpha_and_band_order", test_sixel_rgba_alpha_and_band_order },
        { "test_sixel_palette_over_cap_quantizes_to_dcs", test_sixel_palette_over_cap_quantizes_to_dcs },
        { "test_sixel_rgba_quantizer_preserves_exact_small_palette", test_sixel_rgba_quantizer_preserves_exact_small_palette },
        { "test_sixel_rgba_scales_to_known_cell_pixels", test_sixel_rgba_scales_to_known_cell_pixels },
        { "test_sixel_invalid_cell_pixels_fall_back_to_source_pixels", test_sixel_invalid_cell_pixels_fall_back_to_source_pixels },
        { "test_sixel_clipped_rgba_emits_cropped_dcs", test_sixel_clipped_rgba_emits_cropped_dcs },
        { "test_sixel_clipped_png_decodes_and_crops", test_sixel_clipped_png_decodes_and_crops },
        { "test_sixel_clipped_png_rgba_emits_cropped_dcs", test_sixel_clipped_png_rgba_emits_cropped_dcs },
        { "test_kitty_rgba_without_png_falls_back_placeholder", test_kitty_rgba_without_png_falls_back_placeholder },
        { "test_sixel_clipped_invalid_visible_no_partial_dcs", test_sixel_clipped_invalid_visible_no_partial_dcs },
        { "test_sixel_clipped_palette_uses_visible_crop_not_full_image", test_sixel_clipped_palette_uses_visible_crop_not_full_image },
        { "test_sixel_clears_previous_kitty_placements", test_sixel_clears_previous_kitty_placements },
        { "test_image_protocol_force_none_clears_old_kitty_placements", test_image_protocol_force_none_clears_old_kitty_placements },
        { "test_iterm2_images_emit_osc1337", test_iterm2_images_emit_osc1337 },
        { "test_iterm2_png_rgba_uses_png_payload", test_iterm2_png_rgba_uses_png_payload },
        { "test_iterm2_rgba_without_png_falls_back_placeholder", test_iterm2_rgba_without_png_falls_back_placeholder },
        { "test_iterm2_short_write_transport_chunks", test_iterm2_short_write_transport_chunks },
        { "test_iterm2_clears_previous_kitty_placements", test_iterm2_clears_previous_kitty_placements },
        { "test_iterm2_no_kitty_delete_after_iterm2_frame", test_iterm2_no_kitty_delete_after_iterm2_frame },
        { "test_iterm2_oversized_image_no_partial_emit", test_iterm2_oversized_image_no_partial_emit },
        { "test_iterm2_clipped_draw_falls_back_placeholder", test_iterm2_clipped_draw_falls_back_placeholder },
        { "test_iterm2_clipped_fallback_clears_previous_kitty_placement", test_iterm2_clipped_fallback_clears_previous_kitty_placement },
        { "test_iterm2_invalid_rect_emits_no_escape", test_iterm2_invalid_rect_emits_no_escape },
        { "test_kitty_invalid_rect_does_not_refresh_stale_cleanup", test_kitty_invalid_rect_does_not_refresh_stale_cleanup },
        { "test_pty_hello_exits_on_esc", test_pty_hello_exits_on_esc },
        { "test_paste_cross_feed_terminator", test_paste_cross_feed_terminator },
        { "test_esc_timeout_zero_now", test_esc_timeout_zero_now },
        { "test_msgq_overflow_guard", test_msgq_overflow_guard },
        /* round-7 (Z-series) coverage */
        { "test_open_oom_cleanup", test_open_oom_cleanup },
        { "test_message_api_roundtrip", test_message_api_roundtrip },
        { "test_message_api_reports_oom", test_message_api_reports_oom },
        { "test_layout_siblings", test_layout_siblings },
        { "test_label_hyperlink_wrapper", test_label_hyperlink_wrapper },
        { "test_function_bar_widget", test_function_bar_widget },
        { "test_function_bar_clipped", test_function_bar_clipped },
        { "test_interact_tab_grow_oom", test_interact_tab_grow_oom },
        { "test_hyperlink_set_edges", test_hyperlink_set_edges },
        { "test_run_negative_guards", test_run_negative_guards },
        { "test_app_frame_updates_after_end", test_app_frame_updates_after_end },
        { "test_app_frame_delivers_large_messages", test_app_frame_delivers_large_messages },
        { "test_getters", test_getters },
        { "test_render_stream_chat_like", test_render_stream_chat_like },
        { "test_frame_synchronized_output", test_frame_synchronized_output },
        { "test_mouse_without_drag_emits_no_1002", test_mouse_without_drag_emits_no_1002 },
        { "test_mouse_drag_emits_1002", test_mouse_drag_emits_1002 },
        { "test_mouse_drag_disabled_on_exit", test_mouse_drag_disabled_on_exit },
        { "test_mouse_drag_alone_is_inert", test_mouse_drag_alone_is_inert },
        { "test_transport_accessor", test_transport_accessor },
        { "test_mouse_state_accessor", test_mouse_state_accessor },
        { "test_inline_enter_suppresses_alt_screen", test_inline_enter_suppresses_alt_screen },
        { "test_inline_exit_erases_band", test_inline_exit_erases_band },
        { "test_plain_exit_does_not_erase", test_plain_exit_does_not_erase },
        { "test_inline_paint_two_rows", test_inline_paint_two_rows },
        { "test_inline_paint_single_row", test_inline_paint_single_row },
        { "test_inline_paint_resets_style", test_inline_paint_resets_style },
        { "test_inline_paint_resets_before_row_break", test_inline_paint_resets_before_row_break },
        { "test_inline_paint_null_safe", test_inline_paint_null_safe },
        { "test_inline_commit_lines", test_inline_commit_lines },
        { "test_inline_commit_empty_is_noop", test_inline_commit_empty_is_noop },
        { "test_inline_open_sizes_band", test_inline_open_sizes_band },
        { "test_inline_commit_via_ui", test_inline_commit_via_ui },
        { "test_inline_suspend_resume", test_inline_suspend_resume },
        { "test_inline_trust_protocol", test_inline_trust_protocol },
        { "test_inline_shrink_cleans_below", test_inline_shrink_cleans_below },
        { "test_regression_textarea_scroll_on_grow", test_regression_textarea_scroll_on_grow },
        { "test_key_codepoint_accessor", test_key_codepoint_accessor },
        { "test_slot_style_accessor", test_slot_style_accessor },
        { "test_textarea_fills_background", test_textarea_fills_background },
        { "test_textarea_kill_ops", test_textarea_kill_ops },
        { "test_textarea_word_motion", test_textarea_word_motion },
        { "test_textarea_transpose_and_kill_fwd", test_textarea_transpose_and_kill_fwd },
        { "test_inline_end_skips_unchanged_frame", test_inline_end_skips_unchanged_frame },
        { "test_inline_commit_batches_into_end", test_inline_commit_batches_into_end },
        { "test_inline_parks_cursor_for_focused_input", test_inline_parks_cursor_for_focused_input },
        { "test_inline_cursor_hidden_when_unfocused", test_inline_cursor_hidden_when_unfocused },
        { "test_inline_cursor_hidden_across_repaint", test_inline_cursor_hidden_across_repaint },
        { "test_inline_diff_paint_touches_only_changed_row", test_inline_diff_paint_touches_only_changed_row },
        { "test_inline_diff_paint_edges", test_inline_diff_paint_edges },
        { "test_inline_end_diffs_rows", test_inline_end_diffs_rows },
    };
    size_t i;
    size_t n = sizeof(tests) / sizeof(tests[0]);

    /* --list prints one test name per line so a build system (CTest) can
     * register each case individually; <name> runs exactly one case. */
    if(argc == 2 && strcmp(argv[1], "--list") == 0){
        for(i = 0; i < n; ++i) printf("%s\n", tests[i].name);
        return 0;
    }
    if(argc == 2){
        for(i = 0; i < n; ++i){
            if(strcmp(argv[1], tests[i].name) == 0){
                tests[i].fn();
                if(timui_test_failures != 0)
                    printf("%d CHECK failure(s)\n", timui_test_failures);
                return timui_test_failures == 0 ? 0 : 1;
            }
        }
        fprintf(stderr, "no such test: %s\n", argv[1]);
        return 2;
    }
    if(argc > 2){
        fprintf(stderr, "usage: %s [--list | <test-name>]\n", argv[0]);
        return 2;
    }

    for(i = 0; i < n; ++i) tests[i].fn();

    if(timui_test_failures == 0)
        printf("all tests passed (%zu)\n", n);
    else
        printf("%d CHECK failure(s)\n", timui_test_failures);

    return timui_test_failures == 0 ? 0 : 1;
}
