# SPDX-License-Identifier: MIT
#
# emoji_variation_table(<input> <output>)
#
# Write <output>: the {lo,hi} ranges of the codepoints that U+FE0F asks to draw
# in emoji presentation, read from <input>, the emoji-variation-sequences.txt of
# the Unicode emoji data. A terminal draws such a codepoint with the selector
# as two columns; the selector after any other codepoint changes nothing. The
# table is made when the project is configured, and a change of <input> makes
# CMake configure again.

function(emoji_variation_table input output)
    file(STRINGS "${input}" _lines REGEX "^[0-9A-Fa-f]+ FE0F +; emoji style")
    set(_cps "")
    foreach(_line IN LISTS _lines)
        string(REGEX MATCH "^[0-9A-Fa-f]+" _hex "${_line}")
        math(EXPR _cp "0x${_hex}")
        list(APPEND _cps ${_cp})
    endforeach()
    list(REMOVE_DUPLICATES _cps)
    list(SORT _cps COMPARE NATURAL)
    file(STRINGS "${input}" _date REGEX "^# Date:")
    string(REGEX REPLACE "^# Date: *" "" _date "${_date}")

    set(_body "")
    set(_lo "")
    set(_hi "")
    foreach(_cp IN LISTS _cps)
        if(NOT _lo STREQUAL "")
            math(EXPR _next "${_hi} + 1")
            if(_cp EQUAL _next)
                set(_hi ${_cp})
                continue()
            endif()
            math(EXPR _l "${_lo}" OUTPUT_FORMAT HEXADECIMAL)
            math(EXPR _h "${_hi}" OUTPUT_FORMAT HEXADECIMAL)
            string(APPEND _body "    {${_l},${_h}},\n")
        endif()
        set(_lo ${_cp})
        set(_hi ${_cp})
    endforeach()
    if(NOT _lo STREQUAL "")
        math(EXPR _l "${_lo}" OUTPUT_FORMAT HEXADECIMAL)
        math(EXPR _h "${_hi}" OUTPUT_FORMAT HEXADECIMAL)
        string(APPEND _body "    {${_l},${_h}},\n")
    endif()
    if(_body STREQUAL "")
        message(FATAL_ERROR "${input} lists no emoji variation sequence")
    endif()

    get_filename_component(_name "${input}" NAME)
    file(CONFIGURE OUTPUT "${output}" CONTENT
"/* Generated by cmake/EmojiVariation.cmake from ${_name} (${_date}).
 * Do not edit: it is made again when the project is configured. */
${_body}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${input}")
endfunction()
